import { addTranslation } from '../../../_helpers/Translate';

addTranslation({
  ru: {
    filter_list: 'Показать списком',
    filter_map: 'Показать на карте',
    filter_flat: 'Квартира',
    filter_room: 'Комната',
    filter_price: 'Цена',
    filter_other: 'Другие фильтры',
    filter_from: 'от',
    filter_to: 'до',
    filter_area: 'Площадь в м2',
    filter_floor: 'Этаж',
    filter_houseFloor: 'Этажей в доме',
    filter_residentialComplex: 'Жилой комплекс',
    filter_yearBuilt: 'Год постройки',

    filter_areaAndFloor: 'Этаж и площадь',
    filter_facilities: 'Удобства',
    filter_designerRenovation: 'Дизайнерский ремонт',
    filter_internet: 'Интернет',
    filter_wifi: 'Wi-Fi',
    filter_drying: 'Сушильная машина',
    filter_washer: 'Стиральная машина',
    filter_refrigerator: 'Холодильник',
    filter_dishwasher: 'Посудомойка',
    filter_iron: 'Утюг',
    filter_hairDryer: 'Фен',
    filter_furniture: 'Мебель',
    filter_feedingChair: 'Стул для кормления',
    filter_tv: 'Телевизор',
    filter_conditioning: 'Кондиционер',
    filter_balcony: 'Балкон',
    filter_parking: 'Паркинг',
    filter_safeYard: 'Безопасный двор',
    filter_closedArea: 'Закрытая территория',


    filter_features: 'Особенности',
    filter_canSmoke: 'Можно курить',
    filter_forEvents: 'Подходит для мероприятий',
    filter_animalsAllowed: 'Можно с животными',
    filter_forChildren: 'Подходит для семьи с детьми',
  },
  kk: {},
});
