export const Dictionary = {
  facilities: [
    { code: 'INT', ru_name: 'Интернет' },
    { code: 'WI_FI', ru_name: 'Wi-Fi' },
    { code: 'SU_M', ru_name: 'Сушильная машина' },
    { code: 'ST_M', ru_name: 'Стиральная машина' },
    { code: 'HOL', ru_name: 'Холодильник' },
    { code: 'PSD', ru_name: 'Посудомойка' },
    { code: 'UTG', ru_name: 'Утюг' },
    { code: 'FEN', ru_name: 'Фен' },
    { code: 'MEB', ru_name: 'Мебель' },
    { code: 'TV', ru_name: 'Телевизор' },
    { code: 'ST_KR', ru_name: 'Стул для кормления' },
    { code: 'CON', ru_name: 'Кондиционер' },
    { code: 'DUG', ru_name: 'Датчик угарного газа' },
  ],
  houseRules: [
    { code: 'KUR', ru_name: 'Можно курить' },
    { code: 'MER', ru_name: 'Подходит для мероприятий' },
    { code: 'JIV', ru_name: 'Можно с животными' },
    { code: 'DETI', ru_name: 'Подходит для семьи с детьми' },
  ],
  features: [
    { code: 'VSP', ru_name: 'Высокие потолки' },
    { code: 'DSR', ru_name: 'Дизайнерский ремонт' },
    { code: 'PNO', ru_name: 'Панорамные окна' },
    { code: 'OVK', ru_name: 'Отдельная ванная комната' },
    { code: 'ZKP', ru_name: 'Закрытая парковка' },
    { code: 'PDP', ru_name: 'Подземный паркинг' },
    { code: 'DSM', ru_name: 'Доступная среда для маломобильных' },
    { code: 'BZD', ru_name: 'Безопасный двор' },
    { code: 'ZTR', ru_name: 'Закрытая территория' },
  ],
};
